# Change these first
owner: imagine-ai-project # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: iMagine
    url: https://imagine-ai.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png

  # Dashboards

  - name: iMagine training dashboard
    url: https://dashboard.cloud.imagine-ai.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-imagine.png
    asignees: andresheca
    
  - name: iMagine (dev) training dashboard
    url: https://dashboard.dev.imagine-ai.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-imagine.png
    asignees: andresheca
    
  # PAPI
  - name: Platform API
    url: https://api.cloud.ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-imagine.png
    asignees: IgnacioHeredia

  - name: Platform API (dev)
    url: https://api.dev.ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-imagine.png
    asignees: IgnacioHeredia

  # Cookiecutter
  - name: Repository template generator
    url: https://templates.cloud.ai4eosc.eu/
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-imagine.png
    assignees:
      - vykozlov
      
  # Registry
  - name: Container registry
    url: https://registry.services.ai4os.eu/
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    assigness:
      - mariojmdavid

  # Storage
  - name: AI4OS NextCloud storage
    url: https://share.services.ai4os.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    assigness:
      - mariojmdavid

  # CI/CD
  - name: AI4OS Jenkins CI/CD system
    url: https://jenkins.cloud.ai4eosc.eu/
    icon: https://www.jenkins.io/images/jenkins-logo-title-dark.svg
    assignees: 
      - alvarolopez
      - IgnacioHeredia
      - vykozlov

  # OSCAR UI
  - name: OSCAR UI - Provider UPV/GRyCAP
    url: https://inference.cloud.imagine-ai.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-oscar.jpeg
    asignees: gmolto
    
  # Flowfuse AI4EOSC
  # - name: Flowfuse AI4EOSC - Provider UPV/GRyCAP
  #   url: https://forge.flows.dev.ai4eosc.eu
  #   icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-flowfuse.png
  #   asignees: dieagra

  # Cloud endpoints
  - name: Provider IFCA-LCG2 org.openstack.nova
    url: https://api.cloud.ifca.es:5000/v3
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-ifca.png
    asignees: aidaph

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.imagine-ai.eu
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-imagine.png
  theme: light
  name: iMagine platform status
  introTitle: "Imaging data and services for aquatic science."
  introMessage: This page provides a real time overview of the [iMagine](https://imagine-ai.eu) AI platform and services status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
